apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: oauth2-proxy
spec:
  forwardAuth:
    address: http://oauth2-proxy.kube-system:4180/oauth2/auth_sign_in
    trustForwardHeader: true